library(robotstxt)
library(rvest)
url <- "https://www.flipkart.com/search?q=oppo+mobile&sid=tyy%2C4io&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&as-pos=1&as-type=RECENT&suggestionId=oppo+mobile%7CMobiles&requestId=d8ed7436-3e51-4311-b237-694901831f9f&as-backfill=on"
path <- paths_allowed(url)
web <- read_html(url)
Name <- web%>%html_nodes("._4rR01T")%>%html_text()
View(Name)
Deal_Price <- web%>%html_nodes("._1_WHN1")%>%html_text()
View(Deal_Price)
Ratings <- web%>%html_nodes(".gUuXy-")%>%html_text()
View(Ratings)
mobile.ratings <- data.frame(Name, Deal_Price, Ratings)
View(mobile.ratings)
write.csv(MI.ratings, "Result.csv")
result = read.csv("Result.csv")
View(result)